project:
  type: website

website:
  title: "*Fine-tuning* de LLM en el entorno de las ciencias de la salud"

  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: es



